import type { EventCard } from "./types.ts";

export const EVENTS: EventCard[] = [
  {
    id: "onboarding",
    title: "Распределение",
    category: "career",
    kind: "milestone",
    priority: 100,
    once: true,
    conditions: { minAge: 22, maxAge: 22.24 },
    text: "Тебя распределяют в НИИ Вычислительных Машин. Пропуск уже выписан, стол с терминалом готов. Вопрос только в том, входишь ли ты в систему добровольно.",
    options: [
      {
        id: "accept",
        label: "Принять",
        summary: "Спокойно войти в режим.",
        onSuccess: {
          title: "Система приняла тебя",
          detail: "Первый квартал прошёл без лишних движений.",
          stats: { loyalty: 1, discipline: 1, stress: -1 },
          resources: { money: 1, suspicionRisk: -1 },
        },
      },
      {
        id: "resist",
        label: "Сомневаться",
        summary: "С порога показать характер.",
        onSuccess: {
          title: "Сомнение заметили",
          detail: "Ты не отказался от работы, но сразу заработал репутацию неудобного человека.",
          stats: { intellect: 1, stress: 1, loyalty: -1 },
          resources: { suspicionRisk: 1 },
        },
      },
    ],
  },
  {
    id: "perforated_cards",
    title: "Колода на полу",
    category: "work",
    weight: 10,
    cooldown: 6,
    text: "Пятьсот немаркированных перфокарт рассыпались прямо перед сдачей задачи. Попробуешь собрать порядок по памяти?",
    options: [
      {
        id: "rebuild",
        label: "Собирать самому",
        summary: "Проверка Интеллекта, DC 12.",
        check: { stat: "intellect", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Колода восстановлена",
          detail: "Ты быстро понял, как был устроен алгоритм, но заплатил нервами.",
          stats: { intellect: 1, stress: 2 },
        },
        onFailure: {
          title: "Память подвела",
          detail: "Порядок не сошёлся, а отдел заметил твою панику.",
          stats: { stress: 3, social: -1 },
        },
      },
      {
        id: "report",
        label: "Признаться",
        summary: "Потерять темп, но не доверие.",
        onSuccess: {
          title: "Инцидент оформлен",
          detail: "Работу задержали, зато ты не стал усугублять.",
          stats: { discipline: 1, social: 1, stress: -1 },
          resources: { money: -1 },
        },
      },
    ],
  },
  {
    id: "deadline_push",
    title: "Срок горит",
    category: "work",
    weight: 10,
    cooldown: 5,
    text: "Начальник просит закрыть квартальный проект без переноса. Возьмёшься за жёсткий рывок?",
    options: [
      {
        id: "push",
        label: "Дожать",
        summary: "Проверка Дисциплины, DC 15.",
        check: { stat: "discipline", dc: 15, difficultyLabel: "сложно" },
        onSuccess: {
          title: "Проект сдан",
          detail: "Срок выдержан, премия пришла, а тело запомнило перегруз.",
          stats: { discipline: 1, stress: 3, health: -1 },
          resources: { money: 3 },
          setFlags: ["trusted_by_boss"],
        },
        onFailure: {
          title: "Рывок сорвался",
          detail: "Ты переработал, но всё равно не уложился.",
          stats: { stress: 4, health: -1, social: -1 },
        },
      },
      {
        id: "scope",
        label: "Сузить задачу",
        summary: "Меньше риска, меньше награды.",
        onSuccess: {
          title: "Сделано по минимуму",
          detail: "Сдача прошла спокойнее, хотя никто не назовёт это подвигом.",
          stats: { discipline: 1, stress: 1 },
          resources: { money: 1 },
        },
      },
    ],
  },
  {
    id: "salary_gap",
    title: "Ошибка в ведомости",
    category: "work",
    weight: 7,
    cooldown: 8,
    text: "В зарплатной ведомости ты замечаешь лишние деньги в свою пользу. Исправишь ошибку?",
    options: [
      {
        id: "keep",
        label: "Промолчать",
        summary: "Быстрый плюс к деньгам и риску.",
        onSuccess: {
          title: "Ведомость закрыта",
          detail: "Премия оказалась неофициальной, но след в бумагах остался.",
          resources: { money: 3, suspicionRisk: 2 },
          stats: { stress: 1, loyalty: -1 },
        },
      },
      {
        id: "fix",
        label: "Исправить",
        summary: "Спокойно, но без выгоды.",
        onSuccess: {
          title: "Ошибка исправлена",
          detail: "Бухгалтерия недовольна лишней работой, но к тебе вопросов нет.",
          stats: { discipline: 1, loyalty: 1 },
          resources: { suspicionRisk: -1 },
          setFlags: ["good_reputation"],
        },
      },
    ],
  },
  {
    id: "manual_refactor",
    title: "Ядро на переписку",
    category: "work",
    weight: 8,
    cooldown: 7,
    conditions: { statMin: { intellect: 9 } },
    text: "В системном календаре ошибка, и она уже начинает портить расчёты. Возьмёшься переписывать ядро?",
    options: [
      {
        id: "rewrite",
        label: "Переписать",
        summary: "Проверка Интеллекта, DC 15.",
        check: { stat: "intellect", dc: 15, difficultyLabel: "сложно" },
        onSuccess: {
          title: "Ядро стабилизировано",
          detail: "После нескольких бессонных вечеров система стала надёжнее.",
          stats: { intellect: 2, stress: 2 },
          resources: { money: 2 },
        },
        onFailure: {
          title: "Регресс в проде",
          detail: "Ошибка ушла, но ты принёс две новые.",
          stats: { stress: 3, social: -1, health: -1 },
        },
      },
      {
        id: "defer",
        label: "Отложить",
        summary: "Избежать перегруза, но оставить проблему жить.",
        onSuccess: {
          title: "Проблему перенесли",
          detail: "Ты сохранил силы, но доверие к тебе не выросло.",
          stats: { stress: -1 },
        },
      },
    ],
  },
  {
    id: "foreign_journal",
    title: "Западный журнал",
    category: "learning",
    weight: 8,
    cooldown: 6,
    text: "До тебя дошёл технический журнал с западным алгоритмом. Изучить его официально нельзя, но соблазн велик.",
    options: [
      {
        id: "study",
        label: "Изучить",
        summary: "Проверка Интеллекта, DC 12.",
        check: { stat: "intellect", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Новый приём освоен",
          detail: "Ты быстро разобрался и получил полезный кусок опыта.",
          stats: { intellect: 1, discipline: 1 },
          resources: { suspicionRisk: 2 },
          setFlags: ["access_sensitive_data"],
        },
        onFailure: {
          title: "Журнал заметили",
          detail: "Пользы получилось мало, а след остался.",
          stats: { stress: 2, loyalty: -1 },
          resources: { suspicionRisk: 3 },
          setFlags: ["under_watch"],
        },
      },
      {
        id: "ignore",
        label: "Сдать в архив",
        summary: "Безопасно, но без роста.",
        onSuccess: {
          title: "Архив доволен",
          detail: "Ты сохранил лицо и пропустил короткий путь.",
          stats: { loyalty: 1 },
          resources: { suspicionRisk: -1 },
        },
      },
    ],
  },
  {
    id: "night_course",
    title: "Вечерний курс",
    category: "learning",
    weight: 9,
    cooldown: 6,
    text: "После работы открыли кружок по новому языку программирования. Хватит ли тебя ещё и на это?",
    options: [
      {
        id: "enroll",
        label: "Записаться",
        summary: "Проверка Дисциплины, DC 12.",
        check: { stat: "discipline", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Темп выдержан",
          detail: "Ты встроил учёбу в график и стал заметно собраннее.",
          stats: { discipline: 1, intellect: 1, stress: 1 },
          addTimedEffects: [
            {
              id: "study_cycle",
              label: "Учебный ритм",
              duration: 3,
              visible: true,
              checkBonuses: { intellect: 1 },
              categoryWeights: { learning: 3 },
            },
          ],
        },
        onFailure: {
          title: "Сил не хватило",
          detail: "Пару занятий ты честно посетил, а потом начал выпадать из режима.",
          stats: { stress: 2, health: -1 },
        },
      },
      {
        id: "rest",
        label: "Остаться дома",
        summary: "Спокойнее, но без ускорения.",
        onSuccess: {
          title: "Вечер оставлен себе",
          detail: "Ты не ускорил рост, зато не добил нервную систему.",
          stats: { stress: -1, health: 1 },
        },
      },
    ],
  },
  {
    id: "article_draft",
    title: "Статья в сборник",
    category: "learning",
    weight: 7,
    cooldown: 7,
    conditions: { statMin: { intellect: 10 } },
    text: "Сборник НИИ принимает короткие статьи. Попробуешь оформить свой подход в текст?",
    options: [
      {
        id: "write",
        label: "Написать",
        summary: "Проверка Дисциплины, DC 12.",
        check: { stat: "discipline", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Текст приняли",
          detail: "Статья добавила тебе веса в отделе.",
          stats: { social: 1, intellect: 1 },
          setFlags: ["good_reputation"],
        },
        onFailure: {
          title: "Черновик развалился",
          detail: "Материал оказался сырее, чем казалось вечером.",
          stats: { stress: 2 },
        },
      },
      {
        id: "skip",
        label: "Не сейчас",
        summary: "Оставить силы на текущую работу.",
        onSuccess: {
          title: "Статья подождёт",
          detail: "Ничего не произошло, и это тоже решение.",
          stats: { stress: -1 },
        },
      },
    ],
  },
  {
    id: "mentor_session",
    title: "Разговор с наставником",
    category: "learning",
    weight: 8,
    cooldown: 6,
    conditions: { jobs: ["junior", "engineer"] },
    text: "Старший сотрудник предлагает разобрать с тобой рабочие ошибки без формальностей. Найдёшь на это время?",
    options: [
      {
        id: "listen",
        label: "Слушать",
        summary: "Спокойный рост и шанс на перк.",
        onSuccess: {
          title: "Разбор оказался полезным",
          detail: "Ты разобрал несколько типовых провалов и стал увереннее.",
          stats: { intellect: 1, discipline: 1 },
          addPerks: ["methodical"],
        },
      },
      {
        id: "brush_off",
        label: "Отмахнуться",
        summary: "Сэкономить вечер, но сжечь мост.",
        onSuccess: {
          title: "Совет пропущен",
          detail: "Наставник не обиделся вслух, но выводы сделал.",
          stats: { social: -1, stress: 1 },
        },
      },
    ],
  },
  {
    id: "colleague_help",
    title: "Коллега просит прикрыть",
    category: "social",
    weight: 10,
    cooldown: 5,
    text: "Коллега просит взять часть его расчётов, пока он решает бытовую проблему. Поможешь?",
    options: [
      {
        id: "help",
        label: "Помочь",
        summary: "Проверка Социального капитала, DC 12.",
        check: { stat: "social", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Связь укреплена",
          detail: "Отдел запомнил, что на тебя можно опереться.",
          stats: { social: 1, stress: 1 },
          setFlags: ["good_reputation"],
        },
        onFailure: {
          title: "Помощь вышла криво",
          detail: "Ты хотел поддержать, но заодно создал новый хвост задач.",
          stats: { stress: 2, discipline: -1 },
        },
      },
      {
        id: "refuse",
        label: "Отказать",
        summary: "Сохранить силы, потерять тепло.",
        onSuccess: {
          title: "Холодная дистанция",
          detail: "Ты защитил свой график, но отдел это заметил.",
          stats: { social: -1, stress: -1 },
        },
      },
    ],
  },
  {
    id: "kitchen_talk",
    title: "Разговоры на кухне",
    category: "social",
    weight: 8,
    cooldown: 7,
    text: "После смены коллеги обсуждают, как система ломает нормальную работу. Включишься в разговор?",
    options: [
      {
        id: "join",
        label: "Говорить",
        summary: "Проверка Социального капитала, DC 15.",
        check: { stat: "social", dc: 15, difficultyLabel: "рискованно" },
        onSuccess: {
          title: "Круг принял тебя",
          detail: "Ты не сказал лишнего и стал своим в закрытой компании.",
          stats: { social: 1, loyalty: -1 },
          resources: { suspicionRisk: 2 },
          addPerks: ["connected"],
        },
        onFailure: {
          title: "Слишком громко",
          detail: "Кто-то пересказал разговор дальше, чем нужно.",
          stats: { stress: 2, loyalty: -1 },
          resources: { suspicionRisk: 4 },
          setFlags: ["under_watch"],
        },
      },
      {
        id: "leave",
        label: "Уйти домой",
        summary: "Надёжнее, но суше.",
        onSuccess: {
          title: "Вечер закрыт без последствий",
          detail: "Ты сохранил осторожность и не приобрёл новых связей.",
          stats: { loyalty: 1 },
          resources: { suspicionRisk: -1 },
        },
      },
    ],
  },
  {
    id: "closed_circle",
    title: "Закрытый круг",
    category: "social",
    weight: 6,
    cooldown: 10,
    conditions: { statMin: { social: 10 }, missingFlags: ["under_watch"] },
    text: "Тебя приглашают на неформальную встречу людей, которые двигают решения без бумаги. Войдёшь в круг?",
    options: [
      {
        id: "enter",
        label: "Войти",
        summary: "Проверка Социального капитала, DC 12.",
        check: { stat: "social", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Ты оказался внутри",
          detail: "Новые знакомства делают карьеру менее прямолинейной.",
          stats: { social: 1 },
          resources: { money: 2, suspicionRisk: 1 },
          setFlags: ["trusted_by_boss"],
        },
        onFailure: {
          title: "Свои не признали",
          detail: "Ты не испортил всё, но осадок остался.",
          stats: { social: -1, stress: 1 },
        },
      },
      {
        id: "decline",
        label: "Отказаться",
        summary: "Остаться вне серой зоны.",
        onSuccess: {
          title: "Круг прошёл мимо",
          detail: "Ты сохранил аккуратность и потерял короткий путь.",
          stats: { discipline: 1 },
          resources: { suspicionRisk: -1 },
        },
      },
    ],
  },
  {
    id: "boss_speech",
    title: "Речь на собрании",
    category: "risk",
    weight: 8,
    cooldown: 6,
    text: "На собрании ждут, что кто-то публично поддержит курс руководства. Выйдешь говорить?",
    options: [
      {
        id: "speak",
        label: "Поддержать",
        summary: "Проверка Лояльности, DC 12.",
        check: { stat: "loyalty", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Линия выдержана",
          detail: "Ты выглядел убедительно и снял часть вопросов к себе.",
          stats: { loyalty: 1, social: 1 },
          resources: { money: 1, suspicionRisk: -2 },
        },
        onFailure: {
          title: "Речь вышла деревянной",
          detail: "Сомнение всё равно услышали между строк.",
          stats: { stress: 1, social: -1 },
          resources: { suspicionRisk: 1 },
        },
      },
      {
        id: "silent",
        label: "Промолчать",
        summary: "Меньше участия, больше риска.",
        onSuccess: {
          title: "Пауза затянулась",
          detail: "Ты не соврал, но тишину зафиксировали.",
          stats: { loyalty: -1, stress: 1 },
          resources: { suspicionRisk: 2 },
          setFlags: ["under_watch"],
        },
      },
    ],
  },
  {
    id: "secret_archive",
    title: "Секретный архив",
    category: "risk",
    weight: 7,
    cooldown: 8,
    conditions: { jobs: ["engineer", "senior", "lead"] },
    text: "Тебе предлагают помочь с данными, к которым обычно пускают не всех. Согласишься?",
    options: [
      {
        id: "accept",
        label: "Согласиться",
        summary: "Проверка Интеллекта, DC 15.",
        check: { stat: "intellect", dc: 15, difficultyLabel: "сложно" },
        onSuccess: {
          title: "Доступ получен",
          detail: "Ты разобрался с материалом и стал полезнее, но менее незаметным.",
          stats: { intellect: 1, discipline: 1 },
          resources: { money: 2, suspicionRisk: 3 },
          setFlags: ["access_sensitive_data"],
        },
        onFailure: {
          title: "Доступ обернулся проблемой",
          detail: "Материал оказался тяжелее, а внимание к тебе лишним.",
          stats: { stress: 2, health: -1 },
          resources: { suspicionRisk: 4 },
          setFlags: ["under_watch", "access_sensitive_data"],
        },
      },
      {
        id: "decline",
        label: "Отказаться",
        summary: "Тише и беднее.",
        onSuccess: {
          title: "Ты остался в стороне",
          detail: "Никакой новой власти, но и новых вопросов не прибавилось.",
          stats: { loyalty: 1 },
          resources: { suspicionRisk: -1 },
        },
      },
    ],
  },
  {
    id: "report_request",
    title: "Намёк на донос",
    category: "risk",
    weight: 7,
    cooldown: 9,
    text: "Тебе дают понять, что служебная записка на коллегу упростит жизнь наверху. Напишешь?",
    options: [
      {
        id: "write",
        label: "Написать",
        summary: "Лояльнее системе, хуже людям.",
        onSuccess: {
          title: "Записка ушла",
          detail: "Карьерно это выглядит прагматично, человечески хуже.",
          stats: { loyalty: 2, social: -2, stress: 1 },
          setFlags: ["under_watch"],
        },
      },
      {
        id: "refuse",
        label: "Отказаться",
        summary: "Медленнее, но чище.",
        onSuccess: {
          title: "Ты остался в стороне",
          detail: "Отдел это уважил, а система нет.",
          stats: { social: 1, loyalty: -1 },
          resources: { suspicionRisk: 2 },
        },
      },
    ],
  },
  {
    id: "sanatorium",
    title: "Путёвка в санаторий",
    category: "health",
    weight: 8,
    cooldown: 10,
    conditions: { statMin: { stress: 10 } },
    text: "Профком выделяет путёвку в санаторий. Возьмёшь паузу от отдела?",
    options: [
      {
        id: "go",
        label: "Поехать",
        summary: "Сбросить перегруз за деньги.",
        onSuccess: {
          title: "Нервы отпустило",
          detail: "Квартал стал беднее и заметно тише внутри.",
          stats: { health: 2, stress: -4 },
          resources: { money: -2, suspicionRisk: -1 },
          clearFlags: ["chronic_stress"],
          removeTimedEffects: ["overclocked"],
        },
      },
      {
        id: "stay",
        label: "Остаться",
        summary: "Сохранить деньги и продолжить давить на себя.",
        onSuccess: {
          title: "Отдых отменён",
          detail: "Ты остался в рабочем ритме и заплатил за это собой.",
          stats: { stress: 2, health: -1, discipline: 1 },
        },
      },
    ],
  },
  {
    id: "stimulant",
    title: "Стимулятор «Ударник»",
    category: "health",
    weight: 9,
    cooldown: 7,
    text: "Коллеги предлагают стимулятор для тяжёлых дедлайнов. Примешь?",
    options: [
      {
        id: "take",
        label: "Принять",
        summary: "Короткий буст ценой последствий.",
        onSuccess: {
          title: "Рывок получен",
          detail: "Сегодня работать легче, следующие кварталы тело обсудит отдельно.",
          stats: { stress: 2 },
          addTimedEffects: [
            {
              id: "overclocked",
              label: "Химический разгон",
              duration: 2,
              visible: true,
              perTurn: { stats: { health: -1, stress: 1 } },
              checkBonuses: { discipline: 1, intellect: 1 },
            },
          ],
        },
      },
      {
        id: "refuse",
        label: "Отказаться",
        summary: "Медленнее, но устойчивее.",
        onSuccess: {
          title: "Организм пока твой",
          detail: "Ты сохранил себя и не ускорил квартал химией.",
          stats: { health: 1, stress: -1 },
        },
      },
    ],
  },
  {
    id: "medical_check",
    title: "Обязательный медосмотр",
    category: "health",
    weight: 6,
    cooldown: 9,
    text: "Поликлиника зовёт на обязательный осмотр. Потратишь рабочее время на профилактику?",
    options: [
      {
        id: "go",
        label: "Пройти",
        summary: "Потерять темп, выиграть здоровье.",
        onSuccess: {
          title: "Осмотр не зря",
          detail: "Ты потерял полдня, но вовремя притормозил проблемы.",
          stats: { health: 1, stress: -1 },
          resources: { money: -1 },
        },
      },
      {
        id: "skip",
        label: "Пропустить",
        summary: "Сохранить темп и копить риск.",
        onSuccess: {
          title: "Осмотр отложен",
          detail: "Ты сэкономил время и не решил ничего важного.",
          stats: { discipline: 1, stress: 1 },
          resources: { suspicionRisk: 1 },
        },
      },
    ],
  },
  {
    id: "gymnastics",
    title: "Производственная гимнастика",
    category: "health",
    weight: 7,
    cooldown: 5,
    text: "По радио объявили обязательную гимнастику для всех сотрудников. Присоединишься?",
    options: [
      {
        id: "join",
        label: "Размяться",
        summary: "Небольшой плюс к устойчивости.",
        onSuccess: {
          title: "Польза без драмы",
          detail: "Ты на удивление не пожалел о потраченных десяти минутах.",
          stats: { health: 1, stress: -1 },
        },
      },
      {
        id: "hide",
        label: "Спрятаться",
        summary: "Сохранить лицо проекта, но не тела.",
        onSuccess: {
          title: "Гимнастика прошла мимо",
          detail: "Работа не встала, а спина спасибо не сказала.",
          stats: { discipline: 1, health: -1 },
        },
      },
    ],
  },
  {
    id: "promotion_review",
    title: "Аттестация",
    category: "career",
    kind: "milestone",
    priority: 70,
    once: true,
    conditions: {
      minServiceQuarters: 12,
      jobs: ["junior"],
      statMin: { intellect: 11, discipline: 10 },
    },
    text: "Подошла первая серьёзная аттестация. Попробуешь пробиться на следующую должность?",
    options: [
      {
        id: "go",
        label: "Идти",
        summary: "Проверка Дисциплины, DC 12.",
        check: { stat: "discipline", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Повышение получено",
          detail: "Ты переходишь в инженеры и получаешь чуть больше воздуха.",
          stats: { social: 1, loyalty: 1 },
          resources: { money: 2 },
          setJob: "engineer",
        },
        onFailure: {
          title: "Комиссия не убедилась",
          detail: "Ты остался на месте и забрал с собой только напряжение.",
          stats: { stress: 2, social: -1 },
        },
      },
      {
        id: "wait",
        label: "Подождать",
        summary: "Сохранить лицо и отложить риск.",
        onSuccess: {
          title: "Ты решил не спешить",
          detail: "Формального роста нет, но и болезненного провала тоже.",
          stats: { discipline: 1 },
        },
      },
    ],
  },
  {
    id: "lab_head_offer",
    title: "Предложение завлабства",
    category: "career",
    kind: "milestone",
    priority: 75,
    once: true,
    conditions: {
      minServiceQuarters: 28,
      jobs: ["engineer", "senior"],
      statMin: { social: 11, loyalty: 10 },
      hasFlags: ["trusted_by_boss"],
    },
    text: "Появилось окно на руководящую роль. Это уже не только техника, но и политика. Возьмёшь на себя лабораторию?",
    options: [
      {
        id: "accept",
        label: "Взять",
        summary: "Проверка Социального капитала, DC 15.",
        check: { stat: "social", dc: 15, difficultyLabel: "сложно" },
        onSuccess: {
          title: "Ты стал старшим",
          detail: "Теперь тебе платят больше и смотрят пристальнее.",
          stats: { social: 1, loyalty: 1, stress: 1 },
          resources: { money: 3, suspicionRisk: 1 },
          setJob: "senior",
        },
        onFailure: {
          title: "Роль оказалась преждевременной",
          detail: "Наверху решили, что ты ещё не дотягиваешь.",
          stats: { stress: 2, social: -1 },
        },
      },
      {
        id: "decline",
        label: "Отказаться",
        summary: "Оставить себе меньше власти и меньше надзора.",
        onSuccess: {
          title: "Ты остался ближе к технике",
          detail: "Карьерный рост замедлился, но внутренне стало тише.",
          stats: { intellect: 1, stress: -1 },
        },
      },
    ],
  },
  {
    id: "director_track",
    title: "Этаж руководства",
    category: "career",
    kind: "milestone",
    priority: 80,
    once: true,
    conditions: {
      minServiceQuarters: 44,
      jobs: ["senior"],
      statMin: { loyalty: 13, social: 12 },
      maxSuspicionRisk: 10,
    },
    text: "Руководство ищет человека, который умеет держать линию и отдел. Примешь предложение подняться ещё выше?",
    options: [
      {
        id: "accept",
        label: "Подняться",
        summary: "Проверка Лояльности, DC 15.",
        check: { stat: "loyalty", dc: 15, difficultyLabel: "сложно" },
        onSuccess: {
          title: "Ты вошёл в руководство",
          detail: "Уровень денег и давления одновременно вырос.",
          stats: { loyalty: 1, social: 1, stress: 2 },
          resources: { money: 4, suspicionRisk: -1 },
          setJob: "lead",
        },
        onFailure: {
          title: "Наверх не пустили",
          detail: "Системе понравились не все твои углы.",
          stats: { stress: 2, loyalty: -1 },
        },
      },
      {
        id: "stay",
        label: "Остаться",
        summary: "Сохранить влияние без верхнего этажа.",
        onSuccess: {
          title: "Ты остался на своём уровне",
          detail: "Это не триумф, но и не ловушка.",
          stats: { health: 1, stress: -1 },
        },
      },
    ],
  },
  {
    id: "inspection_memo",
    title: "Служебная беседа",
    category: "inspection",
    kind: "inspection",
    priority: 90,
    cooldown: 4,
    conditions: { minSuspicionRisk: 8 },
    text: "Тебя вызывают на спокойную, но неприятную беседу о настроениях в отделе. Как держишь линию?",
    options: [
      {
        id: "explain",
        label: "Объяснить",
        summary: "Проверка Лояльности, DC 12.",
        check: { stat: "loyalty", dc: 12, difficultyLabel: "обычно" },
        onSuccess: {
          title: "Вопросы сняты",
          detail: "Пока что ты сумел убедить систему в своей предсказуемости.",
          resources: { suspicionRisk: -3 },
        },
        onFailure: {
          title: "Осадок остался",
          detail: "Формально всё закончилось, но наблюдать тебя будут внимательнее.",
          stats: { stress: 2 },
          resources: { suspicionRisk: 2, money: -1 },
          setFlags: ["under_watch"],
        },
      },
      {
        id: "deflect",
        label: "Уйти в общие слова",
        summary: "Проверка Социального капитала, DC 15.",
        check: { stat: "social", dc: 15, difficultyLabel: "рискованно" },
        onSuccess: {
          title: "Ты ушёл без записи",
          detail: "Разговор закончился ничем, и это лучший возможный исход.",
          resources: { suspicionRisk: -2 },
        },
        onFailure: {
          title: "Манёвр не прошёл",
          detail: "Слишком гладко говорить тоже опасно.",
          stats: { stress: 2, loyalty: -1 },
          resources: { suspicionRisk: 3 },
          setFlags: ["under_watch"],
        },
      },
    ],
  },
  {
    id: "inspection_archive",
    title: "Проверка допуска",
    category: "inspection",
    kind: "inspection",
    priority: 95,
    cooldown: 5,
    conditions: { minSuspicionRisk: 10, hasFlags: ["access_sensitive_data"] },
    text: "Проверяющие хотят понять, почему ты оказался рядом с чувствительными данными. Что будешь делать?",
    options: [
      {
        id: "justify",
        label: "Оправдать доступ",
        summary: "Проверка Интеллекта, DC 15.",
        check: { stat: "intellect", dc: 15, difficultyLabel: "сложно" },
        onSuccess: {
          title: "Доступ сохранили",
          detail: "Ты объяснил, зачем был нужен и почему не полез дальше.",
          resources: { suspicionRisk: -2 },
        },
        onFailure: {
          title: "Доступ сужен",
          detail: "Тебя не сломали, но ограничили и запомнили.",
          stats: { stress: 3, social: -1 },
          resources: { suspicionRisk: 3, money: -2 },
          clearFlags: ["trusted_by_boss"],
          setFlags: ["under_watch"],
        },
      },
      {
        id: "confess",
        label: "Сдать доступ",
        summary: "Сбросить давление ценой позиции.",
        onSuccess: {
          title: "Ты отступил",
          detail: "Часть влияния ушла, зато разговор закончился мягче.",
          stats: { loyalty: 1 },
          resources: { suspicionRisk: -3, money: -1 },
          clearFlags: ["access_sensitive_data"],
        },
      },
    ],
  },
  {
    id: "inspection_denunciation",
    title: "Формальная проверка",
    category: "inspection",
    kind: "inspection",
    priority: 110,
    cooldown: 8,
    conditions: { minSuspicionRisk: 14 },
    text: "На стол легла папка по твоему делу. Это уже не беседа, а формальная проверка с возможными последствиями.",
    options: [
      {
        id: "hold",
        label: "Держать линию",
        summary: "Проверка Лояльности, DC 18.",
        check: { stat: "loyalty", dc: 18, difficultyLabel: "рискованно" },
        onSuccess: {
          title: "Ты устоял",
          detail: "Система решила, что пока ты полезнее внутри, чем вне.",
          stats: { stress: 2 },
          resources: { suspicionRisk: -5, money: -2 },
          setFlags: ["under_watch"],
        },
        onFailure: {
          title: "Система закрылась",
          detail: "Проверка закончилась увольнением и фактическим вылетом из игры.",
          endGame: "Арест и служебная чистка. Карьера закончилась в архивной папке.",
        },
      },
      {
        id: "cooperate",
        label: "Сотрудничать",
        summary: "Сохранить себя, потерять уважение.",
        onSuccess: {
          title: "Ты остался внутри",
          detail: "Цена выживания оказалась репутационной.",
          stats: { loyalty: 2, social: -2, stress: 2 },
          resources: { suspicionRisk: -4, money: -1 },
          setFlags: ["under_watch"],
        },
      },
    ],
  },
  {
    id: "burnout",
    title: "Выгорание",
    category: "health",
    kind: "crisis",
    priority: 120,
    cooldown: 8,
    conditions: { statMin: { stress: 18 } },
    text: "Ты слишком долго держал себя на чистой дисциплине. Организм требует остановки прямо сейчас.",
    options: [
      {
        id: "rest",
        label: "Остановиться",
        summary: "Сбросить кризис, потерять деньги и темп.",
        onSuccess: {
          title: "Кризис пережит",
          detail: "Ты выжил, но восстановление обошлось дорого.",
          stats: { stress: -5, health: 1 },
          resources: { money: -3, suspicionRisk: -1 },
          setFlags: ["chronic_stress"],
          addTimedEffects: [
            {
              id: "recovery",
              label: "Восстановление",
              duration: 2,
              visible: true,
              perTurn: { stats: { health: 1, stress: -1 } },
            },
          ],
        },
      },
      {
        id: "push",
        label: "Дожимать себя",
        summary: "Проверка Здоровья, DC 15.",
        check: { stat: "health", dc: 15, difficultyLabel: "сложно" },
        onSuccess: {
          title: "Ты устоял на зубах",
          detail: "Квартал дожат, но цена записана в тело.",
          stats: { health: -2, stress: 2 },
          resources: { money: 2 },
          setFlags: ["chronic_stress"],
        },
        onFailure: {
          title: "Организм выключился",
          detail: "В этот раз у тебя не получилось продавить себя силой воли.",
          endGame: "Выгорание. Ты сошёл с дистанции задолго до пенсии.",
        },
      },
    ],
  },
  {
    id: "collapse",
    title: "Срыв здоровья",
    category: "health",
    kind: "crisis",
    priority: 130,
    cooldown: 8,
    conditions: { statMax: { health: 4 } },
    text: "Здоровье просело слишком низко. Тянуть ещё квартал без вмешательства уже опасно.",
    options: [
      {
        id: "treat",
        label: "Лечиться",
        summary: "Восстановиться за счёт денег.",
        onSuccess: {
          title: "Лечение сработало",
          detail: "Ты вытащил себя, хотя карман этого не простил.",
          stats: { health: 3, stress: -1 },
          resources: { money: -4 },
        },
      },
      {
        id: "ignore",
        label: "Игнорировать",
        summary: "Оставить всё как есть и рискнуть партией.",
        onSuccess: {
          title: "Решение запоздало",
          detail: "Болезнь не стала ждать, пока ты закончишь задачи.",
          endGame: "Болезнь. Карьера оборвалась раньше, чем система успела выдать пенсию.",
        },
      },
    ],
  },
  {
    id: "pension_committee",
    title: "Пенсионный комитет",
    category: "career",
    kind: "milestone",
    priority: 200,
    once: true,
    conditions: { minAge: 60 },
    text: "Комитет подводит итог твоей карьеры, здоровья и отношений с системой. Принимаешь финал?",
    options: [
      {
        id: "accept",
        label: "Принять итог",
        summary: "Завершить карьеру официально.",
        onSuccess: {
          title: "Пенсия оформлена",
          detail: "Система закрыла твоё дело и выписала итог.",
          endGame: "Пенсия. Ты дожил до финала советской технокарьеры.",
        },
      },
    ],
  },
];

export const EVENT_INDEX = new Map(EVENTS.map((event) => [event.id, event]));
